# Generated by Django 6.0.7 on 2026-07-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline"]},
        ),
        migrations.AddField(
            model_name="worker",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="workers_avatar"),
        ),
    ]
