# Generated by Django 6.0.7 on 2026-07-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_alter_task_options_worker_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["username"]},
        ),
    ]
